server:
  port: 8000

spring:
  datasource:
    # \u4EE5\u4E0B\u662F\u6570\u636E\u5E93\u8BBF\u95EE\u914D\u7F6E
    name: mylogin
    url: jdbc:mysql://localhost:3306/mylogin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # \u4EE5\u4E0B\u662F\u8FDE\u63A5\u6C60\u914D\u7F6E
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
      test-while-idle: true
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

# mybatis\u76F8\u5173\u914D\u7F6E
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml